### ISSUE TITLE
Arcane crafting table inserts items in wrong order.

### ISSUE THREAD

**Issue by reworks-org** [GrigLog/ThaumTweaks#1]
When trying to insert item into the crafting table, it will insert them in the wrong order and thus not match any recipe. It also wont stack to existing items instead placing it in a new slot.

Need some kind of pattern mechanic to force items to fit a pattern when being inserted. Maybe an item frame with an item in it attached to the arcane table and it checks that items recipe when inserting?

**Comment by GrigLog** [comment]
What do you mean "wrong order"? Items go from the left upper corner to the right down one, constantly checking if crafting is possible. Example of how it should look like: https://youtu.be/zD_-CW1jxWg. Ive been using crafting patterns from Botania here, but basically the filler can be whatever you want - e.g. paper or nether stars. After all the components have been placed in a grid, just remove the fillers (can be done even with vanilla filtering hoppers) and youll get the result.

**Comment by reworks-org** [comment]
Sorry I wasn't quite clear - this does not work with recipes that have spaces in them, i.e. the workbench charger.
Specifically, when using the method you describe, often the filler items get pulled out and new crafting replaces them, invalidating the reipes.

**Comment by GrigLog** [comment]
Yes, automating the workbench is not as simple as "components go it -> result goes out", but definetly possible, even in vanilla environment (very challenging, but not undoable). Adjust timings, use different blocks/redstone circuits and youll get it. I do not think this a bug, as it works just as intended.

**Comment by GrigLog** [comment]
...Well, youre somewhat right. Most of the players would not appreciate an idea of building large redstone circuits just to make a few stacks of fabric. Adding some kind of universal filler (which is considered as an empty slot and not consumed while crafting) should make it more friendly.

**Comment by reworks-org** [comment]
That sounds like a fair compromise and solution
