### ISSUE TITLE
Suggestion: Give Lapis a source of praecantatio

### ISSUE THREAD

**Issue by ghost** [GrigLog/ThaumTweaks#11]
I've always thought it weird that one of the best sources of praecantatio is an infusion altar. While you can also use Salis Mundus, praecantatio feels like it lacks a good amount of sources in the mod. Adding praecantatio to lapis would help give an effective source to the player. It also makes sense in the game's continuity. It does help apply enchantments to items, after all.

**Comment by GrigLog** [comment]
You can easily get tons of Praecantatio from greatwood logs. Im not if sure aspects in items need revision...
