### ISSUE TITLE
Suggestion: Outerlands

### ISSUE THREAD

**Issue by John0Smith** [GrigLog/ThaumTweaks#12]
I think the Outerlands from Thaumcraft 4 should get added back, just because you normally have after certain time no real hard [combat] challenge in Thaumcraft 6, this also would add a possibility to use the unused boss mobs that are already in the game, but not findable. PS: The blocks for the Outerlands are also already in the game, but mostly not obtainable in survival.

**Comment by Hyxaru** [comment]
While the Outer Lands were certainly unique, the (high quality if you ask me) addon Thaumic Augmentation adds a good replacement for the Outer Lands. Within it's dimension you can find Eldritch Structures, which feature some parts of the familiar Outer Lands maze, and two other dungeon floors and one of the four familiar bosses.
