### ISSUE TITLE
Incompatibility with Bewitchment 1.12.2 - 0.0.22.43 (thaumtweaks 0.2.4.2)

### ISSUE THREAD

**Issue by hamzasarrat** [GrigLog/ThaumTweaks#15]
Crash report: https://pastebin.com/Ze9RvQwq

I think this is a mixin incompatibility. Bewitchment is using mixin 0.8.

**Comment by GrigLog** [comment]
I dont get this crash... My built-it mixin is 0.8.1 and requires 0.8.0. Maybe there is a mod in your pack which has lower mixin version or other requirements? Please post a full log (latest.log)

**Comment by hamzasarrat** [comment]
https://pastebin.com/uGxJ0xUi

**Comment by hamzasarrat** [comment]
Ok never mind, Level Up was using an outdated mixin version, so it crashed everything. Updated it and everything is ok.
