### ISSUE TITLE
Arcane workbench automatically completes the crafts

### ISSUE THREAD

**Issue by alphaNumeric01** [GrigLog/ThaumTweaks#16]
Hello,

I've disabled autocrafting with the arcane workbench but for some reason the craft always auto-completes. When I try to craft an essentia filter, if you place the planks first it automatically turns them all into buttons.

**Comment by Krutoy242** [comment]
Yeah, buttons is such a pain...
It would be so great if automatic crafting would be inverted (with redstone its Enabled. Without - Disabled)

**Comment by GrigLog** [comment]
Arcane workbench autocrafting was re-implemented as a separate block in 0.3
