### ISSUE TITLE
"Tweak crafts" removing modded Infusion crafts

### ISSUE THREAD

**Issue by Krutoy242** [GrigLog/ThaumTweaks#17]
When `B:"Tweak crafts"=true` option enabled, ThaumTweaks removes completely (instead of actually *tweak*) some modded recipes.

Currently discovered: `Primal Metal Ingot` from [**Tinkers' Evolution**](https://www.curseforge.com/minecraft/mc-mods/tinkers-evolution).
This recipe is unavaliable with this option:
<img src="https://i.imgur.com/aFyqeoX.png" width=400>

**Comment by GrigLog** [comment]
Ive just tested it and the recipe was working even with ThaumTweaks turned on. From Tinkers' evolution changelogs I see that there was a problem with missing crafts on their side and that it've been patched.
