### ISSUE TITLE
Arcane Workbench cause significant lag (according Lag Goggles)

### ISSUE THREAD

**Issue by Krutoy242** [GrigLog/ThaumTweaks#18]
When ![](https://git.io/Jt8Pr "Arcane Workbench") Arcane Workbench have items in inventory it causes notable server load:

<img src=https://i.imgur.com/hA8i3Se.png width=500>

Its strange, because it surrounded by Redstone blocks, so should not try to autocraft.

But even without redstone blocks it should not cause such load.

**Comment by GrigLog** [comment]
I know there are a lot of problems with workbench, the whole thing is kinda messy and may take... some time to fix

**Comment by GrigLog** [comment]
Arcane workbench autocrafting was re-implemented as a separate block in 0.3
