### ISSUE TITLE
Built with mixin version too high.

### ISSUE THREAD

**Issue by reworks-org** [GrigLog/ThaumTweaks#2]
Need to built with mixin 0.8 or set the minimum version in the mixin json to 0.8.
Otherwise wont load mixin capabilitys/json on latest forge.

**Comment by GrigLog** [comment]
Are you sure? Launched the mod on latest forge (1.12.2 - 14.23.5.2854) and its fine.,,

**Comment by reworks-org** [comment]
It's likely a conflict with other mods mixin's, which is why it needs to be downgraded.

**Comment by GrigLog** [comment]
It makes sense, thank you!
