### ISSUE TITLE
Arcane workbench no longer works

### ISSUE THREAD

**Issue by DowlingR** [GrigLog/ThaumTweaks#21]
Howdy.

After installing mod, my arcane workbench can no longer be used to produce crafts of either thaumcraft or mundane sorts.
I Attempted to fiddle with the config to no avail.
Only fix, as of now, is to remove the mod.

Current mod list: https://pastebin.com/U7kD6hLf

Let me know if there is anything I can do to help you narrow down the fix.

Thanks.

EDIT: I attempted some more tries at crafting with the mod - as I like the mod and want to keep it.
The problem persisted. however, I WAS able to craft the arcane filler - but NOTHING else.
Attempting to use the arcane filler while crafting other stuff came up nil. 

EDIT: Attempted alpha and beta versions. no difference.
Wanted to also note, I have SEVERAL other thaumcraft addons, which is probably where the issue is coming from. 
A possible easy fix to this would be a config options "prevent this mod from doing anything with arcane workbench=true/false", as I had noticed on the curseforge mod page that one other person did experience this same issue.

**Comment by GrigLog** [comment]
Arcane workbench autocrafting was re-implemented as a separate block in 0.3
