### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by mxnmnm** [GrigLog/ThaumTweaks#22]
I updated to version 0.3 and it crashed my server

https://gist.github.com/mxnmnm/56ef423fde1477a89f03469b27027f45

**Comment by GrigLog** [comment]
Oof
I forgot to make this class client-only... Such a dumb mistake lol. Thanks for the report!

**Comment by GrigLog** [comment]
Thanks, I forgot to add a @SideOnly annotation and it was trying to load GUI on a server
