### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Biviho** [GrigLog/ThaumTweaks#23]
crash on startup after adding thaumtweaks.
tested in a chonky modpack environment, i can test it in a smaller one if needed, but it may take some time
[crash-2022-01-26_14.41.19-client.txt](https://github.com/GrigLog/ThaumTweaks/files/7961660/crash-2022-01-26_14.41.19-client.txt)

**Comment by GrigLog** [comment]
It was a huge headache and Im still not sure why LagGoggles was breaking my class loading lol. Try the latest build from curseforge please.

**Comment by GrigLog** [comment]
Oh damn... Its not working still

**Comment by Biviho** [comment]
I'm not sure it has something to do with lag goggles, i was using them together some versions ago, then removed during the development, but i will check it as soon as i can

Edit: i mean that a crash with lag goggle for my experience usually has nothing to do with lag goggle and removing it cause crash with something else

**Comment by GrigLog** [comment]
The crash you sent is 100% caused by LagGoggles. If there are any other conflicts with the rest of the mods, I will try to fix

**Comment by GrigLog** [comment]
Just use 0.3.2 from CurseForge

**Comment by Biviho** [comment]
tested in my modpack env, and now it's working fine
