### ISSUE TITLE
[Feature Request] Any Thaumcraft file name (Incompatibility with Bansoukou)

### ISSUE THREAD

**Issue by Krutoy242** [GrigLog/ThaumTweaks#24]
I making modpack [E2E-E](https://github.com/Krutoy242/Enigmatica2Expert-Extended).  
To fix [issue with Web and researches](https://github.com/Azanor/thaumcraft-beta/issues/1605), i need to use [Bansoukou](https://www.curseforge.com/minecraft/mc-mods/bansoko) mod, that patches Thaumcraft `.jar` file.

The problem, is after patching, it changes its name to `Thaumcraft-1.12.2-6.1.BETA26-patched.jar`. This makes ThaumTweaks crash on startup with this crashlog:
[debug.log](https://github.com/GrigLog/ThaumTweaks/files/8325634/debug.log)

So, **two requests**:

1. Please add error handling for case when Thaumcraft file was renamed.  
  > Right now i had no clue why my game crashes, and only accidentally understand that it was ThaumTweaks.  
  > It would be nice if game crashed with verbose error, like `Thaumcraft-1.12.2-6.1.BETA26.jar not found for ThaumTweaks` or such.
2. Please add feature to handle renamed files.  
  > It could be glob file search, like `Thaumcraft-*`.
  > Or please just add second possible TC file name as `Thaumcraft-1.12.2-6.1.BETA26-patched.jar` especially for Bansoukou.

**Comment by Rongmario** [comment]
Instead of doing this, update your mod to depend [MixinBooter](https://github.com/LoliKingdom/MixinBooter). the archaic way of manually appending a specific jar on the classpath is very incompatible with the current 1.12.2 ecosystem. Not to mention packing mixins brings forth more problems.

**Comment by GrigLog** [comment]
Ive never heard about this technology before. Using hardcoded file name is obviously a problem so I will try to migrate.

**Comment by Rongmario** [comment]
No problem, its hard getting word out there about 1.12.2 since its pretty much a banned version on Forge's discord, forums and a lot of other places. https://github.com/CleanroomMC will keep you updated if you're still on 1.12.2.

**Comment by GrigLog** [comment]
Uploaded on CurseForge

**Comment by Rongmario** [comment]
Good stuff!

**Comment by GrigLog** [comment]
Does it work? I did some testing but its impossible to try everything

**Comment by Krutoy242** [comment]
I'm gonna test it in a week or so.

**Comment by Krutoy242** [comment]
Well, its actually working! Forget to mention that.
Thank you for the fix.
