### ISSUE TITLE
Infusion Void Metal recipe - is it intended?

### ISSUE THREAD

**Issue by Krutoy242** [GrigLog/ThaumTweaks#25]
Mod information tells that:
> TC more interesting in terms of game progression and more rewarding in terms of difficulty

But why void metal recipe is so **grindy and expert-like**?
![javaw_xAAAVvy7bV](https://user-images.githubusercontent.com/936618/161695412-7026262b-9e5e-4ce3-840f-26e40627b0f9.png)

Original Void Metal Ingot recipe is actually 1 Void Seed
![javaw_9d3CInwZuQ](https://user-images.githubusercontent.com/936618/161696533-923031cc-d38c-425c-b6ce-f13531164ab1.png)

Is it intended?
I mean, on commit message this recipe called "neat", but actually, its just x8 of ingredients.

I am developing an expert modpack, but even for an expert modpack this recipe looks **too grindy** 😅

**Comment by GrigLog** [comment]
Yes, it is intended.
1) Void seeds are much easier to get than in vanilla, as void syphons work 10 times faster and more efficiently.
2) Rare earths are also easier to get as they now scale with Fortune and Refining. Plus youve got a 5*5 miner.
3) Void items are stronger than in vanilla tc, so they should be more expensive.
4) Infusion stones are also buffed, so you can save essentia or make the process of infusion very fast. 

If you dont like the recipe, you can override it with crafttweaker, but Ive played with this recipe and I think it is fairly balanced and not tedious.

**Comment by GrigLog** [comment]
I mean, void metal is supposed to be a manifestation of alien, dangerous power. And his vanilla recipe is just iron + common rift drop... Pathetic

**Comment by Krutoy242** [comment]
Ok, thank you for the answer!

I would probably just change crafts with CT or disable `"Tweak crafts"` completely.

**Comment by GrigLog** [comment]
Btw the rest of the craft changes is straight making stuff less tedious. For example, 5 types of 40 essentia each instead of 7 types of 20 essentia each.
