### ISSUE TITLE
[Suggestion] Arcane Crafter + Workbench Charger compatibility

### ISSUE THREAD

**Issue by Krutoy242** [GrigLog/ThaumTweaks#27]
Some Thaumcraft Recipes require more vis than one chunk can handle.
Modded recipes require even more:

![image](https://user-images.githubusercontent.com/936618/166705772-65dc089e-5722-4f06-9d9a-2bdc7f6dfd4d.png)

It would be cool if i could upgrade Arcane Crafter with Workbench Charger ![image](https://user-images.githubusercontent.com/936618/166705975-8c3ac97c-81c6-44ff-8b36-bf504a6ee2eb.png), so very each recipe of modpack could be automateable

**Comment by GrigLog** [comment]
Nah, Ive played with Thaumic Additons and getting 1500 aura was the easiest thing in it. Find a good group of chunks, use vis regenerators if available, ans dont forget about vis discounting items - in vanilla TC you can get 47% economy at max.

**Comment by GrigLog** [comment]
Yes, you cant automate this, but ugh, mithminite smeltery is not something you will have a lot of

**Comment by Krutoy242** [comment]
Ugh, ok.

I can't show example right now, but even some vanilla TC sometimes asking for lot of vis.
