### ISSUE TITLE
[Suggestion] Tweaking the Theorycrafting minigame

### ISSUE THREAD

**Issue by Vapaman** [GrigLog/ThaumTweaks#28]
I'm putting this here if Codex has no time or motivation to implement this. If anyone here has the skills and motivation to implement this here is the suggestion.

The existing Theorycrafting minigame is pretty lacking in my opinion and not very flexible when making modpacks.
Here is some functionality that would be very helpful:

Adding cards
- Can be generic cards (No category) or categorised cards
- Can have existing categories or custom categories that have been added using this mod
- Can be made to have a required block (eg. bookcase, beacon etc.)
- Other generic functions that are available in the API (inspiration, warp, etc)
- The format would be the same as the API

Tweaking/removing existing cards

- Just the ability to remove or tweak already available cards

I do not know of hard this would be to implement, but the API for the theorycrafting is open and available here:
https://github.com/Azanor/thaumcraft-api/tree/master/research/theorycraft

TC Research patcher issue:
https://github.com/TheCodex6824/ThaumcraftResearchPatcher/issues/15

**Comment by Vapaman** [comment]
Also might I ask; would it be too hard to implement some bug fixes into this mod? There is a mod that implements a small fix, but it seems the author isn't going to update the mod anytime soon.

The mod in question:
https://www.curseforge.com/minecraft/mc-mods/thaumic-fixes

**Comment by GrigLog** [comment]
Fixing bugs means injecting into 90% of TC classes which means very bad compability with other addons, like Thaumic Augmentation, because they try to inject the same stuff. 
About research pages... You basically ask me to fork the other person's project without him even knowing?...

**Comment by Vapaman** [comment]
>Fixing bugs means injecting into 90% of TC classes which means very bad compability with other addons, like Thaumic Augmentation, because they try to inject the same stuff.

:(
 One of my main gripes with TC6 is its general unpolish and the countless amounts of bugs which makes some areas of the mod annoying or practically unusable... *cough* golemancy *cough*. If it doesn't seem like a worthwile job don't bother, especially as COFH TC is nearing its release.

> About research pages... You basically ask me to fork the other person's project without him even knowing?...

I'm not asking you to fork Codex's project. I'm asking you if you could implement it into this mod, similiar to what you did with the pech tweaks. Of course you could fork research patcher if that is easier. If it seems too much don't bother.
