### ISSUE TITLE
Golem can't start infusion

### ISSUE THREAD

**Issue by Dayyer1** [GrigLog/ThaumTweaks#3]
Hello,

I commented on the curseforge page about golems not being able to start infusions. You asked me to post the log.
Is this the right one?

[latest.log](https://github.com/GrigLog/ThaumTweaks/files/5235981/latest.log)

**Comment by GrigLog** [comment]
Are you sure the log is full? Because i dont see anything FML-related... And just in case - do you see an indicator "Vis: 0" in a void robe's description?

**Comment by Dayyer1** [comment]
Yes, I see the Vis: 0.

I tried launching after updating from v2.2 to 2.3, but I crashed.
Here's the log:

[crash-2020-09-21_16.27.30-client.txt](https://github.com/GrigLog/ThaumTweaks/files/5258224/crash-2020-09-21_16.27.30-client.txt)


Also, it turns out that the crafting problem was due to the Thaumic Wands mod.

**Comment by Dayyer1** [comment]
Golems will activate the infusion altar with just Thaumcraft, so I'm going to keep adding mods until I find out what broke it.

**Comment by Dayyer1** [comment]
I'm not sure what did it, but... after updating this mod and removing a few other mods, golems could start infusions. I still need to figure out what mod created the problem.

**Comment by GrigLog** [comment]
Any progress?

**Comment by Dayyer1** [comment]
Not yet. I have an idea I will test later today.
