### ISSUE TITLE
[Bug] Void Robe cleaning warp debuffs

### ISSUE THREAD

**Issue by shoverno2** [GrigLog/ThaumTweaks#30]
Void robe not only extremely OP (that's why I nerf damage resistance to zero for robe... and it's still OP)
But, in exchange, this giving extra warp, when weared.

Verdant Heart Charm (sustainer)
Can't clean warp debuffs
But void robe can and it shouldn't. 
It's price for great (immortality) defence.

Maybe
By studying "(sustainer)" mechanics
You can copy same effect to robe...

**Comment by GrigLog** [comment]
Oh yes, that makes no sense lol

**Comment by GrigLog** [comment]
It is supposed to clean debuffs EXCEPT warp

**Comment by shoverno2** [comment]
> It is supposed to clean debuffs EXCEPT warp

Yep, that's why I mentioned "Verdant Heart Charm"

**Comment by GrigLog** [comment]
Check the latest file on CurseForge

**Comment by shoverno2** [comment]
> Check the latest file on CurseForge

Now this works fine)

And I found many more things that kinda not right...
But those about only warp

I think, I will open more issues)

**Comment by shoverno2** [comment]
Oh, by the way...

Verdant Heart Charm (sustainer)
Not only sustain player character, but even giving extra oxygen while under water

**Comment by shoverno2** [comment]
Oh, is that supposed to "taint poison" being warp effect?
Or you added this one to "black list" too for future ideas?

**Comment by GrigLog** [comment]
I initially wanted it to clear all debuffs but it is... Quite way too much, so you are right, clearing just poison, wither and taint poison is enough. Water breathing I think is too much as well for what void robe already does.
