### ISSUE TITLE
[Bug] Tinker's Evolution incompatibility

### ISSUE THREAD

**Issue by TrashboxBobylev** [GrigLog/ThaumTweaks#34]
Tinker's Evolution allows TiC tools to be enchanted with infusion enchantments. However, due to ThaumTweaks's mixins or some other stuff, infusion enchantments on tinker's tools do not work if both Tinker's Evolution and ThaumTweaks are installed.

Tested on Enigmatica 2 Expert Extended 0.57.0, with Tinker's Evolution 1.0.44 and ThaumTweaks 0.3.5.

**Comment by Krutoy242** [comment]
Issue still actual. Need fix.

**Comment by GrigLog** [comment]
The information provided was not accurate - only block-breaking infusions do not work. And it is more of a vanilla TC bug.

**Comment by Krutoy242** [comment]
I can provide any additional information! How can I help?

**Comment by GrigLog** [comment]
I have fixed already. Will be on CF with some other bug fixes soon

**Comment by GrigLog** [comment]
Check latest file on CF

**Comment by Krutoy242** [comment]
Seems like it fixed! Thank you
