### ISSUE TITLE
[Bug] "Buffed armor" cannot be turned off properly

### ISSUE THREAD

**Issue by Vapaman** [GrigLog/ThaumTweaks#35]
The recharge pedestal accept the armor when "buffed armor" is turned off. It doesn't charge but it is inconsistent with other nonchargable items.
![2022-05-30_01 51 51](https://user-images.githubusercontent.com/77460466/170894637-2eb680f3-3ae1-4b1b-933f-bc54b6b147e9.png)
The text is visible when config is off
![2022-05-30_01 51 56](https://user-images.githubusercontent.com/77460466/170894638-bd4633ea-e7f8-4a18-bbb5-8195308025e2.png)

**Comment by Vapaman** [comment]
There seems to be other things that cannot be properly turned off: 
- Primal Crushers durability buff
- Combining Primordial Pearls/Nodules/Motes

**Comment by GrigLog** [comment]
Turning off merging pearls seems completely pointless to me as you can just not use this QoL feature.

**Comment by GrigLog** [comment]
Check latest file on CF

**Comment by Vapaman** [comment]
> Turning off merging pearls seems completely pointless to me as you can just not use this QoL feature.

I don't think it's completely pointless. It would be nice to have the option for modpack development purposes.

Also sidenote, merging undamaged pearls should be disabled since it doesn't do anything. Examples:
![kuva](https://user-images.githubusercontent.com/77460466/177374219-1f1a50ae-3747-40fe-9ac4-362c3c2b6aa0.png)
![kuva](https://user-images.githubusercontent.com/77460466/177374246-73df9baa-ba3a-4009-bb10-e61d7e05c8fb.png)

Edit: It seems that this behaviour is consistent with vanilla tools

**Comment by Vapaman** [comment]
The Primal Crusher durability is set to 500 properly if 5x5 is off but the buffed repair speed is still there.
