### ISSUE TITLE
[crash] game crashes whenever a void siphon is loaded

### ISSUE THREAD

**Issue by safwe69** [GrigLog/ThaumTweaks#36]
whenever a void siphon is placed the game crashes, whenever a void siphon is in render distance or loaded using a chunkloader the game instantly crashes, this only happens when the config for the siphon is enabled
[crash-2022-07-11_18.54.59-server.txt](https://github.com/GrigLog/ThaumTweaks/files/9086260/crash-2022-07-11_18.54.59-server.txt)

**Comment by xxXCuriositykilledthecatXxx** [comment]
I'm currently having the same problem even with the changes turned off in the config. https://pastebin.com/8bevkzbC
