### ISSUE TITLE
Runic shielding doesn't benefit from Astral Sorcereries runic shielding increases on perk tree with thaumtweaks installed

### ISSUE THREAD

**Issue by Daddybodd** [GrigLog/ThaumTweaks#37]
Turning allow tweaking on/off does nothing.

**Comment by GrigLog** [comment]
Sorry, but this is most likely not possible. ThaumTweaks and Astral Sorcery both try to patch the same class (thaumcraft.common.lib.events.PlayerEvents), so only one can apply. I will think about what is possible here, but this type of incompability is hard to deal with

**Comment by Daddybodd** [comment]
Thank you!


If you can find literally any fix, even if it involves removing sections of the mod, I would be grateful. I just use the ability to change pech trade and the buffed armor.

**Comment by Krutoy242** [comment]
> will think about what is possible here

Option to not patch Runic Shielding at all from ThaumTweaks side would be acceptable.

**Comment by GrigLog** [comment]
Was quite easy actually... Mixins really are powerful
