### ISSUE TITLE
[Looking for Help] Pech Crash

### ISSUE THREAD

**Issue by Handeril** [GrigLog/ThaumTweaks#38]
So, this is currently a bug in my modpack, which is currently making Pechs [Peches?] basically crash the game.

These are the logs:

[crash-2022-07-13_23.38.34-server.txt](https://github.com/GrigLog/ThaumTweaks/files/9109222/crash-2022-07-13_23.38.34-server.txt)
[latest.log](https://github.com/GrigLog/ThaumTweaks/files/9109226/latest.log)

As a note, I do have LolASM and Thaumic Speedup installed in the modpack, but the mod author of those mods has stated that it's likely a Thaumcraft (itself) thing, and this is the only mod that touches how Pechs work (per my suggestion).

I'm wondering if there's a way to fix this crash on my end, if it's something with ThaumTweaks that could be fixed, or if the bug "goes even further beyond" where it can't be fixed.

**Comment by GrigLog** [comment]
Are you sure the crash happens because of ThaumTweaks? The error basically says that 2 different things were accessing pech's ai tasks at the same time in the same tick. I only touch a static object of pech trading interests, no ticking involved.
By the way your pech trades config is wrong. 'Item "thaumcraft:candle_ping" does not exist!' is written in the log.

**Comment by Handeril** [comment]
Does it say which 2 different things are touching Pech AI?

**Comment by GrigLog** [comment]
No, thats just what ConcurrentModificationException means

**Comment by Handeril** [comment]
Would there be a way for me to specifically see what? [Some sort of debug flag or something]

**Comment by GrigLog** [comment]
I think no. So, did you try running without ThaumTweaks?

**Comment by Handeril** [comment]
I just did, and can confirm the error still persists, apologies for the invalid bug report, but thank you for your knowledge of the error.
