### ISSUE TITLE
Possible bug: accidental 32k Vis in all vis-changed chunks

### ISSUE THREAD

**Issue by Krutoy242** [GrigLog/ThaumTweaks#40]
On at least two servers that have my [E2E-E](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) modpack installed, players have noticed that their Vis has suddenly risen to a maximum of 32,000.

After investigating the problem, it seems to be related to Void Armor charging or discharging.

These problems have also been described here:

https://github.com/TheCodex6824/ThaumicAugmentation/issues/320
> ![](https://user-images.githubusercontent.com/79374236/197566905-b146bc04-1fce-42bb-95d3-abed22ae06da.png)
> using the void thaumaturge 3 pieces set together with the "Amulet of Vis" and it caused an insane amount of vis pollution everywhere, setting all the vis to 33.6k to the limit of possible vis in chunks. It is causing me a lot of rifts and taint due to it and there is no way to get rid of all that vis since a whole 16x16 area is contaminated with hundreds of thousands of vis.

https://github.com/Azanor/thaumcraft-beta/issues/1799
> It appears to be caused by having an item with a Vis charge which somehow went over its max limit. IE a Thaumium Fortress armor piece that managed to go over 320 charge. Once that happens, when you place it on the charger, it will rapidly charge the chunk's aura, or if you have an amulet that allows you to recharge anywhere, you will be a walking hotspot of it as long as you are wearing and "recharging" the item. There might be other cases but this is what my issue was, effectively it infinitely charging in reverse without me noticing thanks to the amulet.

I have not been able to reproduce this problem, but it seems to have something to do with the changes ThaumTweaks is making.

**Comment by GrigLog** [comment]
You have linked a thaumcraft issue but it does not mention ThaumTweaks

**Comment by GrigLog** [comment]
Ok, I will try to reproduce

**Comment by Krutoy242** [comment]
> You have linked a thaumcraft issue but it does not mention ThaumTweaks

Yes, because I can't reproduce the issue. But in the links above, ThaumTweaks was also installed.

I suspect that ThaumTweaks may be the problem, although yes, I have no confirmation of that.

**Comment by Krutoy242** [comment]
One of the players investigated the issue a bit. There is his thoughts:

> [...] and it seems like taking tiny amounts of damage would increase the charge beyond the cap, and then recharging the armour would put vis into the aura (while maintaining the armour charge level). The reason tiny damage should increase charge, is because thaumtweaks subtracts the log of the incoming damage from the charge.

**Comment by GrigLog** [comment]
Oh god this is so dumb
