### ISSUE TITLE
[Suggestion] More config options

### ISSUE THREAD

**Issue by Uub112** [GrigLog/ThaumTweaks#5]
Some ideas for additional config options:

- Config to change the vis capacity for the Fortress/Void armors (they tend to be a huge vis drain if you're wearing the amulet that charges vis due to their default capacity),

- Config for disabling the arcane workbench/infusion automation.

**Comment by GrigLog** [comment]
Ive thought nobody would ever want to turn off the automation, but ok.

**Comment by Uub112** [comment]
Tbh, it's mostly the autocrafting for the arcane workbench (what with being so easy to access and all), allowing infusions to be started by golems is pretty cool, but I thought I'd ask for it anyways.
Thanks!
