### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Orinai** [GrigLog/ThaumTweaks#6]
General Crash on Startup, new as of beta 0.2.3. Not sure if it is a general issue or an incompatibility with other thaumcraft addons in the pack, but I have been able to trace it to ThaumTweaks as the cause.

Crashlog here: https://www.dropbox.com/s/jeob0ldc9e6rr5k/crash-2020-09-21_16.19.37-client.txt?dl=0

**Comment by GrigLog** [comment]
Please send a full log ("latest.log")

**Comment by Dayyer1** [comment]
[latest.log](https://github.com/GrigLog/ThaumTweaks/files/5264377/latest.log)

I had the same problem. I realized the text file in the golem issue was the wrong one.

**Comment by Orinai** [comment]
Apologies, Full Log here: [https://www.dropbox.com/s/57f72wk8glmoqsa/latest.log?dl=0](url)

**Comment by Dayyer1** [comment]
I showed a log to somebody and they said "The mod tried to access something that doesn't exist"

**Comment by Dayyer1** [comment]
[latest.log](https://github.com/GrigLog/ThaumTweaks/files/5294794/latest.log)
