### ISSUE TITLE
Right-click harvesting crops causes a crash

### ISSUE THREAD

**Issue by Mario90900** [GrigLog/ThaumTweaks#9]
Hey, I'm getting a client-sided crash when you end up right-click harvesting crops, specifically through Quark adding this it seems. The server seems fine, but the client crashes due to a Invalid hand null exception. You can find the full crashlog here: https://pastebin.com/SKrz9SPV

It appears to be related to Fortune increasing the drops of Rare Earths, so if you are unable to fix it immediately, could we get a config option for this to be able to better test this? It would also be incredibly useful if everything in the mod could have a config for it, either to turn it on or off, or even more fine-grain tweaks. Thanks!

**Comment by GrigLog** [comment]
Thank you, very unexpected NullPointer here

**Comment by Mario90900** [comment]
Thanks a bunch for the quick patch! I ended up doing some more looking into this earlier today, and it seems like getActiveHand() can return null on the client side for some reason. I guess it must be an odd case that comes from the old Singleplayer and Multiplayer merge in vanilla versions back.
